### ISSUE TITLE
Support for ALAC

### ISSUE THREAD

**Issue by stephen** [stephen/nodetunes#1] opened 2014-01-21 18:46 UTC
Currently only supports PCM data; no ALAC support yet.

For AirSonos users: You can work around this on OS X by selecting the system audio instead of direct output from iTunes or AirFoil. You can do this by alt+clicking the volume icon in the top bar, or going through Sound Output in System Preferences.

OS X Volume Icon:
![screen shot 2014-11-25 at 10 21 31 pm](https://cloud.githubusercontent.com/assets/2320890/5196302/6f89c69e-74f1-11e4-89d5-a4526ff33b45.png)

Or via System Preferences:
![screen shot 2014-11-25 at 10 21 51 pm](https://cloud.githubusercontent.com/assets/2320890/5196303/794ee1be-74f1-11e4-8bce-15fcfb80d5b9.png)

**Comment by arimathea** [comment] 2015-02-08 17:05
Would doing a bounty for this feature speed things along a bit?

**Comment by barcar** [comment] 2015-03-04 10:17
Spotify also seems to be affected by this issue - Trying to use AirTunes to send to AirFoil fails with the same error. Sadly the System Audio workaround results in new mail notifications and other system noises being sent.

**Comment by pabloav** [comment] 2015-03-13 01:02
I do wonder about how accurate the theory that Sonos supports streamed ALAC is. See [this thread](https://ask.sonos.com/sonos/topics/which_streaming_protocols_is_supported) with Sonos support where they post the same chart shown above, but end up concluding that only mp3/aac/wma are supported (as HTTP streams). If so the ffmpeg approach will be safest.

**Comment by aspergatus** [comment] 2015-04-23 09:51
I have added this alac-lib: https://github.com/stephank/node-libalac
But I have not tested it yet, will do it this evening: https://github.com/aspergatus/nodetunes

**Comment by auchenberg** [comment] 2015-04-23 13:14
This is interesting @aspergatus. Did you manage to get a working ALAC stream from the server that you could decode? I tried passing it to decoders,and they all choked.

**Comment by aspergatus** [comment] 2015-04-23 13:19
I now managed to get some data our of the decoder. But after 2-3 sucessful decoding, I then get an error. I will ask @stephank  for help https://github.com/stephank/node-libalac/issues/1

**Comment by auchenberg** [comment] 2015-04-23 13:21
Thats cool, great work!

**Comment by stephank** [comment] 2015-04-23 13:26
Oh! I actually wrote that lib because I was trying to integrate it with nodetunes.

But I think the implementation is broken. I don't remember the specifics, only that I fundamentally misunderstood how the encoder works. To get that lib functional probably means a change in API.

I don't think I'll be able to find the time to fix it up, though. Feel free to use it as a starting point and hack it up.

**Comment by microadam** [comment] 2015-05-03 22:34
Any luck with getting this to work? Would be useful for something I am working on, so happy to lend a hand if you could point me in the right direction?

**Comment by aspergatus** [comment] 2015-05-04 06:36
I tried to get https://github.com/audiocogs/alac.js/issues/11 work, but somehow I don't get the decoding correctly. When I have more time to look at that again, I would compare the encoding and decoding process in details, as well as comparing the input pcm -> encoded alac -> decoded pcm to figure out where the error is.

**Comment by mscohen** [comment] 2015-05-07 06:26
I'm sorry to say that I receive the same warnings:

Warning! Codec not supported (96 AppleLossless)
AirSonos currently does not support codecs used by applications such as iTunes or AirFoil.

even if I set up the sound output from alt+click on the volume icon or by selecting the AirSonos devices from System Preferences.

Thanks for all of your work on this.

**Comment by krizor** [comment] 2015-06-07 06:58
found this project from laurent perrin https://github.com/lperrin/node_airtunes which might be usefull according to the alac impementation

**Comment by jishi** [comment] 2015-07-05 21:36
Another pointer regarding ALAC. 

The ALAC support in Sonos is probably limited to container-based files (as someone pointed out). However, they do support FLAC-streaming for music services. I haven't been able to create a FLAC-streaming http endpoint, so haven't had the possibility to test this out. It might also be limited to SMAPI providers, which means that you would probably need to register a developer music service on your system and invoke it that way. 

FLAC and ALAC container based files however might be possible to simulate via a stream (like PCM streaming), but it isn't really straight forward, nor easy to find documentation on how the ALAC stream from AirTunes is composed.

**Comment by jmtatsch** [comment] 2015-08-28 09:38
Once someone tries to airplay directly from iTunes, whole airsonos comes down.
Would it be possible to handle this more gracefully?

```
airsonos
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Searching for Sonos devices on network...

Schlafzimmer (@ 192.168.181.22:1400, RINCON_000E58CC251201400:1)

Search complete. Set up 1 device tunnel.
events.js:87
      throw Error('Uncaught, unspecified "error" event.');
            ^
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at DeviceTunnel.emit (events.js:87:13)
    at NodeTunes.emit (events.js:107:17)
    at announceParse (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:105:31)
    at announce (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:79:7)
    at RtspServer.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtsp.js:62:7)
    at ServerParser.emit (events.js:110:17)
    at ServerParser._emitMessage (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/server-parser.js:28:8)
    at ServerParser.Parser._write (/usr/local/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/parser.js:103:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at ServerParser.Writable.write (_stream_writable.js:217:11)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
```

**Comment by shining01** [comment] 2015-09-20 19:11
Do you think you can create a solution for the ios9 and airsonos problem?  Thanks a lot

**Comment by mihalski** [comment] 2015-10-03 08:47
Is a solution for IOS9 being worked on?

As far as I can understand the problem is ALAC support. Would this library perhaps be of use?
    https://github.com/stephank/node-libalac

Thanks for the great software!

**Comment by auchenberg** [comment] 2015-10-03 08:55
I have great news. 

@wa7son and I got a prototype working last night, where swapped out the ROAP server, to [raop-rtsp-server](https://github.com/watson/raop-rtsp-server) which has FLAC decoding built in.

He extracted the ALAC decoding into this module, https://github.com/watson/alac2pcm, so that might the way to go, but we'd ned to extract the FLAC decoding params from the RTSP stream as [happening here](https://github.com/watson/raop-rtsp-server/blob/master/lib/rtsp-methods.js#L42)

**Comment by buholzer** [comment] 2015-10-03 21:15
Added support for ALAC but device get's disconnected instantly. Looks like there are some new get_parameter requests from iOS 9.0.2.

nodetunes:rtspmethods uncaptured GET_PARAMETER method: volume

**Comment by microadam** [comment] 2015-10-03 21:18
@buholzer got a branch you are working on? I know how to fix

**Comment by microadam** [comment] 2015-10-04 08:48
@auchenberg Hate to tell you, but I am pretty sure the alac2pcm module doesn't work (and for the same reason, neither does the raop-rtsp-server).

If you decode the example alac file from the libalac repo (https://github.com/stephank/node-libalac/blob/master/tests/sine.alac) using alac2pmc (using the same settings as their test.js file) it doesn't produce the same example PCM file (https://github.com/stephank/node-libalac/blob/master/tests/sine.pcm). You are just setting `libalac.packets()` to be the chunk size (which when using the sine.alac example file, you get one `data` event with a chunk size of `33048`) where as when using that example file, you need to be setting `libalac.packets()` to be an array of chunk sizes (i.e exactly what is here: https://github.com/stephank/node-libalac/blob/master/tests/sine.pakt). So on the single `data` event that is produced, you need to pass in an array of 11 different chunk sizes to get the correct output. Where these 11 different chunk sizes come from, I have no idea, I am not sure if its even possible to determine. Interestingly, those 11 different chunk sizes all add up to `33048` (which is what you are currently set to the `libalac.packets()` value to be). So, somehow, you just need to figure out how to split that single `chunk` that occurs on the single `data` event, into the 11 different sizes as mentioned here: https://github.com/stephank/node-libalac/blob/master/tests/sine.pakt

Hope that all makes sense. I have got as far as you guys with doing the decoding and have been stumped at the same place

**Comment by auchenberg** [comment] 2015-10-04 09:08
@stephen It does work. I made a quick and dirty swap of nodetunes with ```roap-rtsp-server```, which is using ```node-alac`` to decode the ALAC stream sent from iTunes and it produces a PCM stream. Just played music in my living room.

Please note that ```roap-rtsp-server``` only works with iTunes (for now).

https://github.com/auchenberg/airsonos/commit/45e950ff2617e0221fd19519fe1f1d53189e2c23

**Comment by microadam** [comment] 2015-10-04 09:17
@auchenberg You are right, it does work from iTunes. I have been testing on an iPhone on iOS9. Do you know what makes it only work from iTunes?

It does seem very odd to me though, that alac2pcm doesn't produce valid PCM when given the example alac file.

**Comment by auchenberg** [comment] 2015-10-04 09:21
@microadam Don't not exactly why ```roap-rtsp-server``` only works with iTunes, but the theory is that it doesn't something wrong in the ANNOUNCE handshake for AirFoil, iOS. I know @wa7son it working on it.

Totally. That's quite odd, maybe the wrong FLAC Cookie is used? ``road-rtsp-server`` is extracting it on the fly, https://github.com/watson/raop-rtsp-server/blob/master/lib/rtsp-methods.js#L47

**Comment by buholzer** [comment] 2015-10-04 20:43
@microadam have it in a local copy, but can't really test. Any clue how the response to the volume request should look like?

**Comment by fluffypony** [comment] 2015-10-05 19:00
@auchenberg I *think* you're seeing a red herring. As described here: https://github.com/stephen/airsonos/issues/177 the AirPlay server can be discovered by iTunes, but not as an AirPlay device in iOS 9 or El Capitan's sound output selection.

**Comment by buholzer** [comment] 2015-10-05 19:22
@auchenberg @fluffypony if you include the 'vn=65537' parameter in the mDNS advertisement as suggested by @easen you can see the server as AirPlay device in iOS 9 and El Capitan's sound output.

https://github.com/stephen/airsonos/issues/177#issuecomment-137929058

**Comment by microadam** [comment] 2015-10-05 19:55
it is a red herring.

If you put in all the same txt records on nodetunes as on here:

https://github.com/watson/raop-rtsp-server/blob/master/index.js#L33-L49

Then it will work just fine

**Comment by auchenberg** [comment] 2015-10-05 20:55
@microadam @fluffypony @buholzer I'm a bit unsure what you mean by a "red herring" (pardon my non-native english), but we do indeed have ALAC-to-PCM decoding working from ```iTunes``` with ```roap-rtsp-server```.

I just added a speaker example here https://github.com/auchenberg/raop-rtsp-server/blob/speaker-example/examples/speaker.js, which you are welcome to run it, and let me know how it works.

Why ```roap-rtsp-server``` doesn't work with AirFoil, iOS or OSX is still a pending task of @watson's

**Comment by microadam** [comment] 2015-10-06 20:48
As an update, I have ALAC support working for iOS9 on both nodetunes and raop-rtsp-server thanks to the work and pointers from auchenberg and wa7on. 

I just need to tidy it up, sort out a few PR to various dependencies and then I will submit a PR here (and to roap-rtsp-server) with the fixes. Should all be done by end of the weekend if not before

**Comment by buholzer** [comment] 2015-10-07 01:33
@microadam Very nice, let me know if you want me to test it out.

**Comment by xuncia** [comment] 2015-10-07 15:07
@microadam let me know either and I'll test it too!

**Comment by microadam** [comment] 2015-10-08 18:23
ALAC support added here: https://github.com/stephen/nodetunes/pull/36

Only works on node 0.10 as it turns out, as one of the binary dependencies needs upgrading, which might take a while

**Comment by auchenberg** [comment] 2015-10-08 18:26
:tada: :balloon: :birthday:

**Comment by KinelyAdmin** [comment] 2015-10-09 00:33
Hi guys, Thank you for your great work. Just started looking for a solution 2 days ago and found this project. I installed my binary via "port" on mac.  I am not sure if your latest code is reflected there as I re-installed today and still getting the same error as before "i.e." does not support codecs used by applications as iTunes" , will ports repo be updated soon?  Also, I am using latest nodejs v0.12.7, I take it from microadam comment, it will not work on it and I need to downgrade?

**Comment by microadam** [comment] 2015-10-09 13:19
@KinelyAdmin This fix currently only exists in my PR. It hasn't been pushed out to the mainline of this project yet

**Comment by microadam** [comment] 2015-10-11 19:44
Just waiting for this PR to be merged (https://github.com/watson/alac2pcm/pull/2) and ALAC support should then work on node 0.10, 0.12 and 0.4.

Will update #36 with changes to the alac2pcm dep once its been merged. If it doesn't get merged soon, then I will just link it directly to my version

**Comment by microadam** [comment] 2015-10-12 08:28
PR #36 updated with support for 0.10, 0.12 and 4.1

**Comment by vincentpalita** [comment] 2015-10-12 13:25
@microadam : works great!! Thank you :)

**Comment by vkoi81** [comment] 2015-10-12 22:00
@microadam  - kudos for all the work you put in. Same to all the other contributors!

I am a completely noob to all of this so please forgive my lack of understanding. I have airsonos running on a raspberry pi 2. Is your fix built into the npm airsonos install? Wondering if I reinstall airsonos, if it will work on ios 9.
Or is it just a matter of replacing the package.json file with the one you created?

Thanks.

**Comment by mihalski** [comment] 2015-10-13 06:59
I also don't understand what I need to do to get this working. As far as I can tell there have been no changes to stephank/node-libalac for a year and if I try to install its explicitly it fails.

**Comment by microadam** [comment] 2015-10-13 07:33
Guys, nothing has changed with AirSonos or the mainline of nodetunes yet. @stephen has yet to review my PR let alone merge it yet. Until it is merged and a new version of nodetunes and then a new version of AirSonos is released, nothing will work. In the meantime, if you understand node and the dependency tree (and depending on how you installed nodetunes or Airsonos and where from) you maybe able to update all the dependencies to point to my working version of nodetunes to get things working before @stephen releases any official versions of anything. 

If you are unsure, then wait for @stephen to release a new version which contains my fixes

**Comment by vincentpalita** [comment] 2015-10-13 10:23
@vkoi81 : i replace the nodetunes modules inside /usr/local/lib/node_modules/airsonos/nodes_modules by the version of @microadam (manually) then I ran inside the nodetunes folder : npm install

Then it all worked fine again :) 
Just you cannot have an audio output as of now in OSX. You only get an Airplay device in iTunes.

**Comment by vkoi81** [comment] 2015-10-13 12:40
@microadam  -Thanks for the info. I will wait for @Stephen..sucks being a windows person in a Linux world :)
@vincentpalita  - Can you tell me which specific files you replaced? I was looking at the files here:
https://github.com/microadam/nodetunes/commit/cc0333e3dbe2b844964e85a050cec0a1f73207e8 - package.json. and
https://github.com/microadam/nodetunes/commit/9c216d488365c8ec9d51735376db7f3b2812d089 - rtspmethods.json and server.js

I am assuming this fix is to have airplay functionality in ios 9?

**Comment by twentworth12** [comment] 2015-10-13 14:46
@vincentpalita your suggest worked great for me on my Mac, but didn't work on my Raspberry Pi. Regardless, I've got a solution that works!

**Comment by xuncia** [comment] 2015-10-13 15:14
@vincentpalita thanks for the suggestion it works great! and thanks @microadam and @stephen

**Comment by czekaj** [comment] 2015-10-13 16:06
@microadam how about direct audio out from OSX to AirSonos? Does it require separate implementation to make it compatible with El Capitan?

**Comment by microadam** [comment] 2015-10-13 16:28
@czekaj I assume by direct audio out, you mean alt clicking the volume icon in OSX and choosing an airplay device?

If so, then this works fine for me with using el capitan and plain nodetunes. I don't run Airsonos, so it may be an incompatibility with that somewhere...

**Comment by czekaj** [comment] 2015-10-13 17:16
@microadam yes, that's what I mean. I haven't tested it yet since I'm still on Yosemite but @vincentpalita said it doesn't work at the moment.
That's why I was wondering if it needs a separate fix.

**Comment by microadam** [comment] 2015-10-13 20:23
Working for me without going via Airsonos and just running nodetunes (don't use Airsonos or actually have sonos to test with). For those that it's not working for, can you get any error logs that you may have? Also, does it just not show up in the list of AirPlay devices? If not, are you sure you are running a version with the latest changes?

**Comment by twentworth12** [comment] 2015-10-13 20:30
@microadam Works on Node 0.12.5 on my Mac, doesn't work on 0.12.7 on my Raspberry PI. I see the AirPlay devices, but when I play something, airsonos crashes with

/home/pi/.linuxbrew/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/alac2pcm/node_modules/libalac/index.js:119
  this._dec = new binding.Decoder({
              ^
Error: ALAC error: unknown error
    at Error (native)
    at new ALACDecoder (/home/pi/.linuxbrew/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/alac2pcm/node_modules/libalac/index.js:119:15)
    at Object.exports.decoder (/home/pi/.linuxbrew/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/alac2pcm/node_modules/libalac/index.js:179:10)
    at new module.exports (/home/pi/.linuxbrew/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/alac2pcm/index.js:34:21)
    at announceParse (/home/pi/.linuxbrew/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:135:25)
    at announce (/home/pi/.linuxbrew/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtspmethods.js:81:7)
    at RtspServer.<anonymous> (/home/pi/.linuxbrew/lib/node_modules/airsonos/node_modules/nodetunes/lib/rtsp.js:60:7)
    at ServerParser.emit (events.js:110:17)
    at ServerParser._emitMessage (/home/pi/.linuxbrew/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/server-parser.js:28:8)
    at ServerParser.Parser._write (/home/pi/.linuxbrew/lib/node_modules/airsonos/node_modules/nodetunes/node_modules/httplike/lib/parser.js:103:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at ServerParser.Writable.write (_stream_writable.js:217:11)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)

**Comment by tiberiumihai** [comment] 2015-10-14 08:43
I got it working. Here is how:

Open terminal and type this commands:
```
npm uninstall airsonos
npm install airsonos -g
cd /usr/local/lib/node_modules/airsonos/
vi package.json
```
Press i to be able to change the file.
Find this line:
```
"nodetunes": "0.2.1",
```
and change it with this line:
```
"nodetunes": "git://github.com/microadam/nodetunes.git",
```

Type :wq to save the file and exit vi.

```
npm install
```

Wait a few seconds and then type

```
airsonos
```

It's working just fine!

Thanks microadam!

**Comment by vkoi81** [comment] 2015-10-14 15:00
@tiberiumihai  - Thanks for this. I was able to make these changes and ios9 detects Sonos speakers as Airplay.
I have the same issue as @twentworth12 where airsonos crashes when attempting to stream audio. Still investigating. I will play with this a little more since I have a better understanding of the dependencies.

Thanks @microadam for your solution!

**Comment by skippster** [comment] 2015-10-14 18:47
I get the same, I can see the devices, but it crashes with the error below when i start to stream audio.
![pi](https://cloud.githubusercontent.com/assets/14895138/10494081/3096c4e6-72ac-11e5-8133-df1bb1343cbf.JPG)

**Comment by microadam** [comment] 2015-10-14 19:53
What version of node and what OS are you guys having this issue on?

**Comment by skippster** [comment] 2015-10-14 19:56
Raspbian 8.0
node v0.10.40

**Comment by vkoi81** [comment] 2015-10-14 20:39
Raspbian 7.8
Node 0.12.1

**Comment by scotty92fr** [comment] 2015-10-14 21:12
Thanks https://github.com/microadam, but I have the same issue than twentworth

Rasbian : debian version 8.0
Node : 4.0.0

**Comment by dgoldblatt** [comment] 2015-10-14 22:31
@microadam @tiberiumihai Thanks for the updates!  Confirmed working on OS X 10.10.4 with node 0.10.40 (reverted with npm) and iOS 9.1b5 as well as streaming from iTunes 12.3 on 10.11.

Very nice work.

**Comment by changlongzj** [comment] 2015-10-15 02:50
Working nicely in OSX El Capitan 10.11, with the caveat @tiberiumihai mentioned!

**Comment by jspiro** [comment] 2015-10-15 02:56
Works in El Cap here too!

**Comment by czekaj** [comment] 2015-10-15 21:27
I just upgraded to El Capitan. Updated homebrew, reinstalled current node. Then followed instructions from @tiberiumihai and everything works flawlessly! Direct audio out from OSX, iOS AirPlay, everything.

Thanks @microadam ! Where can I send a donation? :)

**Comment by vkoi81** [comment] 2015-10-15 22:32
@czekaj - What version of node are you running?
I am running node 0.10.40 and npm 1.4.28. Are you also utilizing airsonos for sonos speakers?

Thanks

**Comment by czekaj** [comment] 2015-10-15 22:40
I'm not on my Mac at the moment but it's the latest node from Homebrew, which appears to be v4.2.1, looking at their Github repository. And yes, I'm using airsonos.

**Comment by vkoi81** [comment] 2015-10-15 22:54
@czekaj I suspect the crashing issue has something to do with the raspberry pi. I assume you are running airsonos on a mac which seems to have no issues.
Has anyone gotten this to work on a raspberry pi?

**Comment by jgale** [comment] 2015-10-16 14:59
FWIW, this works flawlessly for me on a Mac running 10.9, Node 4.1.2 (installed from nodejs.org package), and AirSonos (latest master code from GitHub). Great work @microadam!

**Comment by pgtruesdell** [comment] 2015-10-16 17:52
I haven't contributed to this package, but wanted to let you know that this fix by @microadam has worked.

**Comment by atchoooo** [comment] 2015-10-16 18:21
I followed @tiberiumihai instructions and it's the same for me. Works flawlessly for me on a Mac running 10.11 Airplaying from an iPhone with 9.0.2.  Thanks a lot !

**Comment by JonnyBoy333** [comment] 2015-10-16 20:59
Everything is working great here. Thanks so much @microadam.

**Comment by shining01** [comment] 2015-10-17 05:34
Unfortunately on raspberry pi 2 it didn't work like @tiberiumihai described. iTunes on OSX El Capitan can see the devices but chrashes with the error "Can't get a connection to airplay device. An unknown error is occured (-15000). On iOS9.0.2 i can't see the devices. Please help us. i need airsonos for my musician work (metronom e.g.). i have the same opinion like @pgtruesdell. For the great work we would like to give you a donation. Thanks

**Comment by shining01** [comment] 2015-10-17 05:54
on the airsonos console on raspberry pi 2 i can see the message (if i klick play on itunes):
Airsonos currently does not support codecs used by applications such as iTunes or AirFoil.

**Comment by ponywhite** [comment] 2015-10-17 11:15
I'm sorry guys but I don't get anything of what you're saying. I'm not a coding specialist, but I was still able to set up AirSonos on OS X Yosemite using node and code on terminal windows. Now that I updated to El Capitan, my Sonos speakers don't show on my computer/iTunes anymore.

I tried following what @tiberiumihai said above, but it's not working.
What am I supposed to do, step by step, please?

My system:
OS X 10.11
iTunes 12.3.0.44
node-v0.10.33 or node-v4.2.1 (I downloaded both)

Help me please.

**Comment by fluffypony** [comment] 2015-10-17 11:36
@ponywhite if you're not familiar with nodejs and it's package manager then I strongly suggest waiting until this is fully tested and AirSonos is updated. I know it's frustrating to have functionality break from an operating system update, but be assured that the contributors on this project will finalise this within a couple of weeks.

**Comment by ponywhite** [comment] 2015-10-17 16:12
@fluffypony Ok :(
Thank you!

**Comment by microadam** [comment] 2015-10-17 16:30
Looks like there is some issues with this running on a raspberry pi. Will try and take a look at some point over the next week. The people that are having issues with raspberry pi, what model are you using?

**Comment by shining01** [comment] 2015-10-17 17:30
I use Raspberry PI 2 Model B Mainboard Sockel (A 900MHz, Quad-core, ARM Cortex-A7 CPU, 4x USB, Full HDMI)

**Comment by scotty92fr** [comment] 2015-10-17 17:46
I triés on a 
raspberry model B With raspbian (debian version 8) 
Node v 4.0.0

**Comment by jacaru** [comment] 2015-10-17 17:48
Fixed raspberry pi with https://github.com/stephank/node-libalac/pull/4

**Comment by buholzer** [comment] 2015-10-17 18:43
Can confirm the error described by @skippster at https://github.com/stephen/nodetunes/issues/1#issuecomment-148153932 and the corresponding fix stephank/node-libalac#4 that works on
- raspberry Pi 2 Model B
- Debian 7.8
- node v0.10.39

Big thanks to @jacaru for the raspberry Pi fix and @microadam @watson @auchenberg for all the great alac work!

**Comment by twentworth12** [comment] 2015-10-17 18:49
Confirmed++

For those trying to get this to work, make sure you run "make" in "/airsonos/node_modules/nodetunes/node_modules/alac2pcm/node_modules/libalac" after updating the file in "/airsonos/node_modules/nodetunes/node_modules/alac2pcm/node_modules/libalac/ALAC/codec"

**Comment by buholzer** [comment] 2015-10-17 19:01
I am getting audio skips, looks like the cpu usage is higher with alac than it was with pcm. Have to investigate more.

**Comment by vkoi81** [comment] 2015-10-17 20:31
@twentworth12
Did you replace the entire ALAC directory with the one from @jakaru?
That's what I did and then ran npm install libilac followed by running make from within the codec directory. Trying to run make from libilac directory have me a message that said no files available to run make. 
I'm sorry but would you mind sharing the steps you took on the pi?

Thanks.

**Comment by vkoi81** [comment] 2015-10-17 20:57
I also tried replacing the endionportable.c file that's inside the codec directory and then ran make from inside the codec directory as that is where I saw the make file. 
My pi is still crashing. I'm running raspbian Jessie, not sure if that matters. 

@twentworth12 @buholzer @jacaru

**Comment by vkoi81** [comment] 2015-10-17 21:25
I was able to get this to work. I reinstalled airsonos and now I have no issues playing from ios9. 

Thanks to everyone!!!!

**Comment by dsarel10** [comment] 2015-10-18 03:07
Does anyone the cause of this error I'm getting, after following tiberiumihai's instructions?  I'm running Ubuntu 14.04 with node 0.12.4.

```
Searching for Sonos devices on network...


/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise.js:677
            throw e;
                  ^
Error: Method Not Allowed
    at maybeWrapAsError (/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/util.js:70:12)
    at /usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise_resolver.js:41:50
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:112:20
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/logicalDevice.js:106:22
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:251:17
    at done (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:126:15)
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:32:16
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:248:21
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/async/lib/async.js:572:34
    at /usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/volumeListener.js:24:14
    at Listener.<anonymous> (/usr/local/lib/node_modules/airsonos/node_modules/sonos/lib/events/listener.js:123:9)
    at Request.self.callback (/usr/local/lib/node_modules/airsonos/node_modules/sonos/node_modules/request/request.js:129:22)
```

**Comment by microadam** [comment] 2015-10-18 08:38
I have updated the dependency tree on my version of nodetunes to contain the raspberry pi fix, so for those that are having issues; you should be just be able to point at that, and not have to start messing around with replacing directories and rerunning make

**Comment by scotty92fr** [comment] 2015-10-18 11:28
many thanks  microadam, but I have tried modifying

**Comment by shining01** [comment] 2015-10-18 12:57
it works on raspberry pi 2 model b with the modification of @microadam. But i get the sound only on one sonos box. i have two sonos in stereo mode. After a few seconds (e.g. 30s) the sound stagnate for a milli second. that repeats sometimes. After e.g. 1 minute sound breaks completely. No sound is comming out.

**Comment by skippster** [comment] 2015-10-18 16:31
Thanks @microadam

I can now get audio but I get a glitch every few seconds. I have tried overclocking the pi2 to 900 and it makes no difference.  

Any ideas anyone??

**Comment by microadam** [comment] 2015-10-18 17:05
Not tried nodetunes on a raspberry pi, but it's quite possible that the ALAC decoding is quite CPU intensive, so a pi might just not be powerful enough for it. Node is single threaded, so it won't be able to take advantage of the multi cores.

**Comment by shining01** [comment] 2015-10-18 17:22
the cpu usage is on raspberry pi 2 between 50% and 75% on cpu 1.  I hope you can optimize it please. 
Thanks

**Comment by microadam** [comment] 2015-10-18 17:31
I doubt there is much that can be done in terms of optimisation of the ALAC decoding. The decoder is provided by apple, so I imagine it's already pretty optimal.

**Comment by shining01** [comment] 2015-10-18 18:46
Thanks Adam for the clarification

**Comment by microadam** [comment] 2015-10-18 19:14
Having said all that, I could very well be wrong :) past my abilities though I am afraid!

**Comment by shining01** [comment] 2015-10-18 19:40
But there is one  Thing that i realised. ALAC exists since 2004. on the Last OS X 10.10 Yosemite airsonos Works very well on raspberry pi 2. i Hope there is anywhere an optimization possible. Thanks

**Comment by luxio** [comment] 2015-10-18 22:28
Thx @tiberiumihai, your instructions  https://github.com/stephen/nodetunes/issues/1#issuecomment-147976411 works well with OS X 10.11.

**Comment by buholzer** [comment] 2015-10-19 02:31
Update for the raspberry users, I had the skips / glitches as described by @skippster in https://github.com/stephen/nodetunes/issues/1#issuecomment-149028336. 

Updated my Raspberry Pi 2 Model B to the following configuration: 
- Raspbian GNU/Linux 8.0 (jessie)
- Node v4.2.1

Do not have any audio skips / glitches anymore and cpu usage is about 50%-60%.

**Comment by skippster** [comment] 2015-10-19 20:29
Thanks @buholzer.
Confirmed no skips/glitches after upgrading from Node 0.10 to 4.2.1

**Comment by vkoi81** [comment] 2015-10-19 23:22
Plus one,,,everything works flawlessly on Raspbian v8 - Jessie and Node 4.2.1
No skips, decent CPU.

Thanks everyone!!!

**Comment by shining01** [comment] 2015-10-20 06:05
Thanks @buholzer.
Confirmed no skips/glitches after upgrading from Node 0.10 to 4.2.1 and update from debain 7 to 8.
Thanks a lot to all of you guys

**Comment by jacaru** [comment] 2015-10-20 10:32
We are lucky to get by with 60% CPU use and it all depends on what other stuff the raspberry is doing in the background.

There are three relatively CPU intensive tasks the airsonos package does as a whole:

1. Decrypt RTP stream (this is likely the most intensive I think)
2. Decode ALAC
3. Encode MP3

3 is done in the thread pool, out of the event loop, and that's good. There  can be some contention between 1 and 2 which run in the main event loop. Probably moving 2 to the thread pool can improve things a bit on some marginal situations.

**Comment by scotty92fr** [comment] 2015-10-21 07:04
I have tried again on my Raspberry model B with overclocking to maximum and updated node to 4.2.1, it works very well, I just lose the first 25 second at the beginning of the connection. thanks @microadam and everyone you save my Raspberry !

**Comment by ponywhite** [comment] 2015-10-23 14:23
@stephen, please. When will you release a new version of AirSonos which works with El Capitan and iOS9. It’s a pain in the ass trying to follow all the advices that are posted here. We’re just waiting for you, dude!

**Comment by jsalceda** [comment] 2015-10-31 18:47
Thanks @tiberiumihai. I followed your instructions and it works perfect.
My system is:
- Macbook  running OS X El Capitan10.11.1, and iTunes 12.3.1.23
- iPhone 6 with iOS 9.1
- iPad Air with iOS 9.1. 

Thanks a lot !

**Comment by OlzKennett** [comment] 2015-11-01 13:37
Hey, this is some great work... I have a problem though. I'm blind so using the command line to fix airsonos is a little difficult, I was wondering if there was a way of going through finder on mac instead to edit thecode? I'm kinda green when it comes to such things so forgive my stupidity... I'd really like to get this working,, mainly so I can get my play 1s working with my apple tv, as I'm sure you can understand, good sound is very important to me. Thanks in advance. O

**Comment by OlzKennett** [comment] 2015-11-01 15:00
I managed to find the file and change the line within finder, should that work or does it need to compile again or something? it seems to call another package with the replaced line sowill this just happen when I type airsonos in terminal? 

I could just wait for the package update I guess. :)

**Comment by tiberiumihai** [comment] 2015-11-01 17:19
After you've changed the nodetunes dependency you will have to type the command:

npm install

into airsonos directory to update the airsonos dependencies.

After doing that you sould be able to use airsonos from terminal.

Cheers!

**Comment by OlzKennett** [comment] 2015-11-01 18:39
Bang on, thanks so much, thought there would be a step missing Now working very nicely, though dropping out a little but I think that’s just my isp.

Thanks again.
Oliver
07989945386

**Closed** 2015-11-02 02:47 UTC
Labels: enhancement

**Comment by jelockwood** [comment] 2015-12-17 13:38
@microadam 

With regards to decoding ALAC being CPU intensive. I am by no means a programmer myself but my understanding is that ALAC decoding should not be excessively CPU intensive as that was the specific goal when Apple originally designed it. Remember the original implementation of ALAC dates back to the original iPod which of course in modern terms has an incredibly feeble processor. ALAC encoding on the other hand might be more CPU intensive but not decoding. Supposedly the main difference between FLAC and ALAC is that ALAC is supposed to be less demanding to do decoding than FLAC. (Both produce similar size files and of course identical quality files.)

If you are decoding a PCM stream and then re-encoding it to ALAC to send to Sonos then this might be the issue as this is then contrary to the comments here not decoding ALAC but rather encoding to ALAC.

Now what may also be applicable is where the ALAC library your using comes from. Originally ALAC was closed source and the first third-party code to process ALAC was done by reverse engineering ALAC by David Hammerton. It is quite likely this original source was nowhere near as optimised as Apple's then private code. More recently Apple of course did make ALAC open source and published the code on macosforge.org. It is quite likely any ffmpeg or similar ALAC libraries pre-date Apple making ALAC open-source.
